version: "3.4"
services:
  naming_server:
    build: ./naming_server
    ports:
      - "22322:22322"


  storage_server:
    build: ./storage_server
    depends_on:
      - naming_server


  client:
    build: ./client
    depends_on:
      - naming_server
    volumes:
      - /tmp/files /files